//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Jackal
{
    [Serializable]
    public class StopStatusMsg : Message
    {
        public const string k_RosMessageName = "jackal_msgs/StopStatus";
        public override string RosMessageName => k_RosMessageName;

        //  Additional Stop information
        public Std.HeaderMsg header;
        public bool stop_power_status;
        //  True indicates the stop loop is operational (ie. it is powered).
        public bool external_stop_present;
        //  True indicates a external stop has been plugged in.

        public StopStatusMsg()
        {
            this.header = new Std.HeaderMsg();
            this.stop_power_status = false;
            this.external_stop_present = false;
        }

        public StopStatusMsg(Std.HeaderMsg header, bool stop_power_status, bool external_stop_present)
        {
            this.header = header;
            this.stop_power_status = stop_power_status;
            this.external_stop_present = external_stop_present;
        }

        public static StopStatusMsg Deserialize(MessageDeserializer deserializer) => new StopStatusMsg(deserializer);

        private StopStatusMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.stop_power_status);
            deserializer.Read(out this.external_stop_present);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.stop_power_status);
            serializer.Write(this.external_stop_present);
        }

        public override string ToString()
        {
            return "StopStatusMsg: " +
            "\nheader: " + header.ToString() +
            "\nstop_power_status: " + stop_power_status.ToString() +
            "\nexternal_stop_present: " + external_stop_present.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
