//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Jackal
{
    [Serializable]
    public class SetDomainIdRequest : Message
    {
        public const string k_RosMessageName = "jackal_msgs/SetDomainId";
        public override string RosMessageName => k_RosMessageName;

        public byte domain_id;
        //  ROS_DOMAIN_ID

        public SetDomainIdRequest()
        {
            this.domain_id = 0;
        }

        public SetDomainIdRequest(byte domain_id)
        {
            this.domain_id = domain_id;
        }

        public static SetDomainIdRequest Deserialize(MessageDeserializer deserializer) => new SetDomainIdRequest(deserializer);

        private SetDomainIdRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.domain_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.domain_id);
        }

        public override string ToString()
        {
            return "SetDomainIdRequest: " +
            "\ndomain_id: " + domain_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
