//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Jackal
{
    [Serializable]
    public class SetDomainIdResponse : Message
    {
        public const string k_RosMessageName = "jackal_msgs/SetDomainId";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        //  Indicate successful update of domain ID
        public string message;
        //  Error/Success message

        public SetDomainIdResponse()
        {
            this.success = false;
            this.message = "";
        }

        public SetDomainIdResponse(bool success, string message)
        {
            this.success = success;
            this.message = message;
        }

        public static SetDomainIdResponse Deserialize(MessageDeserializer deserializer) => new SetDomainIdResponse(deserializer);

        private SetDomainIdResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "SetDomainIdResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
